/**
 * TanStack Query data layer (design D4/D5) — the ONLY module screens use for
 * server data.
 *
 * One `useQuery` per resource and one `useMutation` per write operation.
 * Every query key carries the active user id (D4); while no user is active the
 * queries are disabled and the mutations reject without sending a request.
 * Every mutation invalidates EXACTLY the key prefixes the D5 map names:
 *
 *   | hook                | invalidated prefixes                                              |
 *   | ------------------- | ----------------------------------------------------------------- |
 *   | useUploadDocument   | ["assets", uid]                                                   |
 *   | useCreateAccount    | ["accounts", uid]                                                 |
 *   | useCreateMovement   | ["movements", uid], ["accounts", uid]                             |
 *   | usePatchDescription | ["movements", uid], ["accounts", uid]                             |
 *   | useDeleteMovement   | ["movements", uid], ["accounts", uid]                             |
 *   | useLinkMovement     | ["movements", uid], ["accounts", uid]                             |
 *   | useUnlinkMovement   | ["movements", uid], ["accounts", uid]                             |
 *   | useUploadStatement  | ["batches", uid], ["batch", uid, id]                              |
 *   | useCommitBatch      | ["batches", uid], ["batch", uid, id], ["movements", uid], ["accounts", uid] |
 *   | useDiscardBatch     | ["batches", uid], ["batch", uid, id]                              |
 *   | useDeleteAsset      | ["assets", uid], ["asset", uid, id]                               |
 *   | useRestoreAsset     | ["assets", uid], ["asset", uid, id]                               |
 *   | useMergeAsset       | ["assets", uid], ["asset", uid, survivorId], ["asset", uid, duplicateId] |
 *   | usePatchAsset       | ["assets", uid], ["asset", uid, id]                               |
 *   | useAdd              | ["assets", uid], ["batches", uid]                                 |
 *   | useApproveReview    | ["reviews", uid], ["review", uid, id], ["assets", uid]            |
 *   | useRejectReview     | ["reviews", uid], ["review", uid, id]                             |
 *
 * The `["movements", uid]` prefix deliberately carries NO filter element, so
 * it matches every filter variant of the movements key.
 *
 * All API calls now go through typed per-operation functions from client.ts
 * (generated by orval), replacing the previous apiJson/apiVoid path-string bridge.
 */
import { keepPreviousData, useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { QueryClient, UseMutationResult, UseQueryResult } from '@tanstack/react-query';
import * as client from './client';
import { uploadDocument, uploadStatement } from './upload';
import type { UploadDocumentResult } from './upload';
import { ApiError } from './errors';
import { useActiveUser } from '../../context/active-user';
import type {
  Account,
  AddItemOutcome,
  Asset,
  CommitSummary,
  CreateAccountRequest,
  CreateMovementInput,
  Document,
  ImportBatch,
  MergeRequest,
  Movement,
  PatchAssetRequest,
  SearchResultsPage,
} from './schema';

// ---------------------------------------------------------------------------
// Query keys (D5) — every key carries the active user id (D4)
// ---------------------------------------------------------------------------

/** `["assets", uid]` — the active user's assets. */
export function assetsKey(userId: string | null): readonly ['assets', string | null] {
  return ['assets', userId];
}

/** `["asset", uid, id]` — one asset. */
export function assetKey(userId: string | null, assetId: string): readonly ['asset', string | null, string] {
  return ['asset', userId, assetId];
}

/** `["asset-docs", uid, id]` — the documents of one asset. */
export function assetDocsKey(
  userId: string | null,
  assetId: string,
): readonly ['asset-docs', string | null, string] {
  return ['asset-docs', userId, assetId];
}

/** `["accounts", uid]` — the active user's finance accounts. */
export function accountsKey(userId: string | null): readonly ['accounts', string | null] {
  return ['accounts', userId];
}

/**
 * Movement list filters in UI shape. The wire names (`account_id`, `from`,
 * `to`) are mapped in the query function; the key keeps the UI shape
 * (D5: `{accountId, from, to}`).
 */
export interface MovementFilterInput {
  readonly accountId?: string;
  readonly from?: string;
  readonly to?: string;
}

/** Always all three keys present (undefined when unset) — stable key shape. */
function normalizeFilters(filters: MovementFilterInput | undefined): MovementFilterInput {
  return { accountId: filters?.accountId, from: filters?.from, to: filters?.to };
}

/** `["movements", uid, {accountId, from, to}]` — movements with the filters. */
export function movementsKey(
  userId: string | null,
  filters?: MovementFilterInput,
): readonly ['movements', string | null, MovementFilterInput] {
  return ['movements', userId, normalizeFilters(filters)];
}

/**
 * Prefix of EVERY movements key (any filter set) — the D5 invalidation unit.
 * Without the filter element it matches all filter variants.
 */
export function movementsPrefix(userId: string | null): readonly ['movements', string | null] {
  return ['movements', userId];
}

/** `["batches", uid]` — the import batch history. */
export function batchesKey(userId: string | null): readonly ['batches', string | null] {
  return ['batches', userId];
}

/** `["batch", uid, id]` — one import batch. */
export function batchKey(userId: string | null, batchId: string): readonly ['batch', string | null, string] {
  return ['batch', userId, batchId];
}

// ---------------------------------------------------------------------------
// Request plumbing
// ---------------------------------------------------------------------------

/**
 * Run `fetchWithUser` for the active user. Queries are only enabled, and the
 * UI only offers mutations, while a user is active, so the rejection is
 * defensive; it keeps the fetchers null-free without non-null assertions.
 */
function requireUser<T>(userId: string | null, fetchWithUser: (user: string) => Promise<T>): Promise<T> {
  if (userId === null) {
    return Promise.reject(new Error('No active user selected'));
  }
  return fetchWithUser(userId);
}

// ---------------------------------------------------------------------------
// Queries
// ---------------------------------------------------------------------------

/** `["assets", uid]` — the active user's assets. */
export function useAssets(): UseQueryResult<Asset[], Error> {
  const { activeUser } = useActiveUser();
  return useQuery({
    queryKey: assetsKey(activeUser),
    enabled: activeUser !== null,
    queryFn: () => requireUser(activeUser, (user) => client.listAssets(user)),
  });
}

/** `["asset", uid, id]` — one asset. */
export function useAsset(assetId: string): UseQueryResult<Asset, Error> {
  const { activeUser } = useActiveUser();
  return useQuery({
    queryKey: assetKey(activeUser, assetId),
    enabled: activeUser !== null,
    queryFn: () => requireUser(activeUser, (user) => client.getAsset(user, assetId)),
  });
}

/** `["asset-docs", uid, id]` — the documents of one asset. */
export function useAssetDocuments(assetId: string): UseQueryResult<Document[], Error> {
  const { activeUser } = useActiveUser();
  return useQuery({
    queryKey: assetDocsKey(activeUser, assetId),
    enabled: activeUser !== null,
    queryFn: () => requireUser(activeUser, (user) => client.listAssetDocuments(user, assetId)),
  });
}

/** `["accounts", uid]` — the active user's finance accounts. */
export function useAccounts(): UseQueryResult<Account[], Error> {
  const { activeUser } = useActiveUser();
  return useQuery({
    queryKey: accountsKey(activeUser),
    enabled: activeUser !== null,
    queryFn: () => requireUser(activeUser, (user) => client.listAccounts(user)),
  });
}

/**
 * `["movements", uid, {accountId, from, to}]` — movements with the supplied
 * filters. `placeholderData: keepPreviousData` keeps the previous list on
 * screen while a filter change re-queries (D5).
 */
export function useMovements(filters?: MovementFilterInput): UseQueryResult<Movement[], Error> {
  const { activeUser } = useActiveUser();
  const normalized = normalizeFilters(filters);
  const params = {
    account_id: normalized.accountId,
    from: normalized.from,
    to: normalized.to,
  };
  return useQuery({
    queryKey: movementsKey(activeUser, filters),
    enabled: activeUser !== null,
    placeholderData: keepPreviousData,
    queryFn: () => requireUser(activeUser, (user) => client.listMovements(user, params)),
  });
}

/** `["batches", uid]` — the import batch history. */
export function useBatches(): UseQueryResult<ImportBatch[], Error> {
  const { activeUser } = useActiveUser();
  return useQuery({
    queryKey: batchesKey(activeUser),
    enabled: activeUser !== null,
    queryFn: () => requireUser(activeUser, (user) => client.listImportBatches(user)),
  });
}

/** `["batch", uid, id]` — one import batch with its parsed lines. */
export function useBatch(batchId: string): UseQueryResult<ImportBatch, Error> {
  const { activeUser } = useActiveUser();
  return useQuery({
    queryKey: batchKey(activeUser, batchId),
    enabled: activeUser !== null && batchId !== '',
    queryFn: () => requireUser(activeUser, (user) => client.getImportBatch(user, batchId)),
  });
}

// ---------------------------------------------------------------------------
// Mutations (D5 invalidation map)
// ---------------------------------------------------------------------------


/**
 * Invalidate EXACTLY the given key prefixes (D5). One `invalidateQueries`
 * call per prefix keeps the "exactly these prefixes" contract observable.
 */
function invalidatePrefixes(queryClient: QueryClient, prefixes: ReadonlyArray<readonly unknown[]>): void {
  for (const prefix of prefixes) {
    // Fire-and-forget: invalidation only schedules refetches.
    void queryClient.invalidateQueries({ queryKey: prefix });
  }
}

/** The D5 prefixes shared by every movement mutation. */
function movementInvalidations(userId: string): ReadonlyArray<readonly unknown[]> {
  return [movementsPrefix(userId), accountsKey(userId)];
}

/**
 * D5: document upload → `["assets", uid]`. The upload goes through the XHR
 * helper (D6) so progress can be reported.
 */
export interface UploadDocumentVariables {
  readonly file: File;
  readonly onProgress?: (event: { loaded: number; total: number }) => void;
}

export function useUploadDocument(): UseMutationResult<UploadDocumentResult, ApiError, UploadDocumentVariables> {
  const { activeUser } = useActiveUser();
  const queryClient = useQueryClient();
  return useMutation<UploadDocumentResult, ApiError, UploadDocumentVariables>({
    mutationFn: ({ file, onProgress }: UploadDocumentVariables) =>
      requireUser(activeUser, (user) => uploadDocument(user, file, onProgress ?? (() => undefined))),
    onSuccess: () => {
      if (activeUser === null) {
        return;
      }
      invalidatePrefixes(queryClient, [assetsKey(activeUser)]);
    },
  });
}

/**
 * D5: statement upload → `["batches", uid]`, `["batch", uid, id]`. The upload
 * goes through the XHR helper (D6) so progress can be reported.
 */
export interface UploadStatementVariables {
  readonly accountId: string;
  readonly file: File;
  readonly onProgress?: (event: { loaded: number; total: number }) => void;
}

export function useUploadStatement(): UseMutationResult<ImportBatch, ApiError, UploadStatementVariables> {
  const { activeUser } = useActiveUser();
  const queryClient = useQueryClient();
  return useMutation<ImportBatch, ApiError, UploadStatementVariables>({
    mutationFn: ({ accountId, file, onProgress }: UploadStatementVariables) =>
      requireUser(activeUser, (user) => uploadStatement(user, accountId, file, onProgress ?? (() => undefined))),
    onSuccess: (batch) => {
      if (activeUser === null) {
        return;
      }
      invalidatePrefixes(queryClient, [batchesKey(activeUser), batchKey(activeUser, batch.id)]);
    },
  });
}

/**
 * D5: account create → `["accounts", uid]`.
 */
export function useCreateAccount(): UseMutationResult<Account, ApiError, CreateAccountRequest> {
  const { activeUser } = useActiveUser();
  const queryClient = useQueryClient();
  return useMutation<Account, ApiError, CreateAccountRequest>({
    mutationFn: (body: CreateAccountRequest) =>
      requireUser(activeUser, (user) => client.createAccount(user, body)),
    onSuccess: () => {
      if (activeUser === null) {
        return;
      }
      invalidatePrefixes(queryClient, [accountsKey(activeUser)]);
    },
  });
}

/**
 * D5: movement create → `["movements", uid]` + `["accounts", uid]`
 * (a new movement changes account balances).
 */
export function useCreateMovement(): UseMutationResult<Movement, ApiError, CreateMovementInput> {
  const { activeUser } = useActiveUser();
  const queryClient = useQueryClient();
  return useMutation<Movement, ApiError, CreateMovementInput>({
    mutationFn: (body: CreateMovementInput) =>
      requireUser(activeUser, (user) => client.createMovement(user, body)),
    onSuccess: () => {
      if (activeUser === null) {
        return;
      }
      invalidatePrefixes(queryClient, movementInvalidations(activeUser));
    },
  });
}

/** Variables for the description PATCH. */
export interface PatchDescriptionVariables {
  readonly movementId: string;
  readonly description: string;
}

/**
 * D5: description patch → `["movements", uid]` + `["accounts", uid]`.
 */
export function usePatchDescription(): UseMutationResult<Movement, ApiError, PatchDescriptionVariables> {
  const { activeUser } = useActiveUser();
  const queryClient = useQueryClient();
  return useMutation<Movement, ApiError, PatchDescriptionVariables>({
    mutationFn: ({ movementId, description }: PatchDescriptionVariables) =>
      requireUser(activeUser, (user) =>
        client.patchMovement(user, movementId, {
          description,
          amount: '',
          currency: '',
          occurred_on: '',
          kind: '',
          source_account_id: '',
          destination_account_id: '',
        }),
      ),
    onSuccess: () => {
      if (activeUser === null) {
        return;
      }
      invalidatePrefixes(queryClient, movementInvalidations(activeUser));
    },
  });
}

/** Variables identifying one movement (delete/unlink). */
export interface MovementIdVariables {
  readonly movementId: string;
}

/**
 * D5: movement delete → `["movements", uid]` + `["accounts", uid]`.
 */
export function useDeleteMovement(): UseMutationResult<void, ApiError, MovementIdVariables> {
  const { activeUser } = useActiveUser();
  const queryClient = useQueryClient();
  return useMutation<void, ApiError, MovementIdVariables>({
    mutationFn: ({ movementId }: MovementIdVariables) =>
      requireUser(activeUser, (user) => client.deleteMovement(user, movementId)),
    onSuccess: () => {
      if (activeUser === null) {
        return;
      }
      invalidatePrefixes(queryClient, movementInvalidations(activeUser));
    },
  });
}

/** Variables for the movement–document link. */
export interface LinkMovementVariables {
  readonly movementId: string;
  readonly documentId: string;
}

/**
 * D5: movement link → `["movements", uid]` + `["accounts", uid]`.
 */
export function useLinkMovement(): UseMutationResult<Movement, ApiError, LinkMovementVariables> {
  const { activeUser } = useActiveUser();
  const queryClient = useQueryClient();
  return useMutation<Movement, ApiError, LinkMovementVariables>({
    mutationFn: ({ movementId, documentId }: LinkMovementVariables) =>
      requireUser(activeUser, (user) =>
        client.linkMovement(user, movementId, { document_id: documentId }),
      ),
    onSuccess: () => {
      if (activeUser === null) {
        return;
      }
      invalidatePrefixes(queryClient, movementInvalidations(activeUser));
    },
  });
}

/**
 * D5: movement unlink → `["movements", uid]` + `["accounts", uid]`.
 */
export function useUnlinkMovement(): UseMutationResult<void, ApiError, MovementIdVariables> {
  const { activeUser } = useActiveUser();
  const queryClient = useQueryClient();
  return useMutation<void, ApiError, MovementIdVariables>({
    mutationFn: ({ movementId }: MovementIdVariables) =>
      requireUser(activeUser, (user) => client.unlinkMovement(user, movementId)),
    onSuccess: () => {
      if (activeUser === null) {
        return;
      }
      invalidatePrefixes(queryClient, movementInvalidations(activeUser));
    },
  });
}

/** Variables identifying one import batch (commit/discard). */
export interface BatchIdVariables {
  readonly batchId: string;
}

/**
 * D5: batch commit → `["batches", uid]` + `["batch", uid, id]` AND — commit
 * writes movements — `["movements", uid]` + `["accounts", uid]`.
 */
export function useCommitBatch(): UseMutationResult<CommitSummary, ApiError, BatchIdVariables> {
  const { activeUser } = useActiveUser();
  const queryClient = useQueryClient();
  return useMutation<CommitSummary, ApiError, BatchIdVariables>({
    mutationFn: ({ batchId }: BatchIdVariables) =>
      requireUser(activeUser, (user) => client.commitImportBatch(user, batchId)),
    onSuccess: (_summary, variables) => {
      if (activeUser === null) {
        return;
      }
      invalidatePrefixes(queryClient, [
        batchesKey(activeUser),
        batchKey(activeUser, variables.batchId),
        movementsPrefix(activeUser),
        accountsKey(activeUser),
      ]);
    },
  });
}

/**
 * D5: batch discard → `["batches", uid]` + `["batch", uid, id]` (no movements
 * are written, so movements/accounts stay untouched).
 */
export function useDiscardBatch(): UseMutationResult<ImportBatch, ApiError, BatchIdVariables> {
  const { activeUser } = useActiveUser();
  const queryClient = useQueryClient();
  return useMutation<ImportBatch, ApiError, BatchIdVariables>({
    mutationFn: ({ batchId }: BatchIdVariables) =>
      requireUser(activeUser, (user) => client.discardImportBatch(user, batchId)),
    onSuccess: (_batch, variables) => {
      if (activeUser === null) {
        return;
      }
      invalidatePrefixes(queryClient, [batchesKey(activeUser), batchKey(activeUser, variables.batchId)]);
    },
  });
}

/** Variables identifying one asset (delete/restore/patch). */
export interface AssetIdVariables {
  readonly assetId: string;
}

/**
 * D5: asset soft-delete → `["assets", uid]` + `["asset", uid, id]`.
 */
export function useDeleteAsset(): UseMutationResult<void, ApiError, AssetIdVariables> {
  const { activeUser } = useActiveUser();
  const queryClient = useQueryClient();
  return useMutation<void, ApiError, AssetIdVariables>({
    mutationFn: ({ assetId }: AssetIdVariables) =>
      requireUser(activeUser, (user) => client.deleteAsset(user, assetId)),
    onSuccess: (_data, variables) => {
      if (activeUser === null) {
        return;
      }
      invalidatePrefixes(queryClient, [assetsKey(activeUser), assetKey(activeUser, variables.assetId)]);
    },
  });
}

/**
 * D5: asset restore → `["assets", uid]` + `["asset", uid, id]` (the restored
 * asset reappears in the list and its detail changes).
 */
export function useRestoreAsset(): UseMutationResult<Asset, ApiError, AssetIdVariables> {
  const { activeUser } = useActiveUser();
  const queryClient = useQueryClient();
  return useMutation<Asset, ApiError, AssetIdVariables>({
    mutationFn: ({ assetId }: AssetIdVariables) =>
      requireUser(activeUser, (user) => client.restoreAsset(user, assetId)),
    onSuccess: (_asset, variables) => {
      if (activeUser === null) {
        return;
      }
      invalidatePrefixes(queryClient, [assetsKey(activeUser), assetKey(activeUser, variables.assetId)]);
    },
  });
}

/** Variables for merging a duplicate asset into a survivor. */
export interface MergeAssetVariables {
  readonly assetId: string;
  readonly duplicateAssetId: string;
}

/**
 * D5: asset merge → `["assets", uid]` + `["asset", uid, survivorId]` AND
 * `["asset", uid, duplicateId]` (the duplicate's row changes to merged-into,
 * so its detail must refetch too).
 */
export function useMergeAsset(): UseMutationResult<Asset, ApiError, MergeAssetVariables> {
  const { activeUser } = useActiveUser();
  const queryClient = useQueryClient();
  return useMutation<Asset, ApiError, MergeAssetVariables>({
    mutationFn: ({ assetId, duplicateAssetId }: MergeAssetVariables) => {
      const body: MergeRequest = { duplicate_asset_id: duplicateAssetId };
      return requireUser(activeUser, (user) => client.mergeAsset(user, assetId, body));
    },
    onSuccess: (_asset, variables) => {
      if (activeUser === null) {
        return;
      }
      invalidatePrefixes(queryClient, [
        assetsKey(activeUser),
        assetKey(activeUser, variables.assetId),
        assetKey(activeUser, variables.duplicateAssetId),
      ]);
    },
  });
}

/** Variables for the asset correction PATCH. */
export interface PatchAssetVariables {
  readonly assetId: string;
  readonly body: PatchAssetRequest;
}

/**
 * D5: asset patch (user corrections incl. `asset_category`) →
 * `["assets", uid]` + `["asset", uid, id]`.
 */
export function usePatchAsset(): UseMutationResult<Asset, ApiError, PatchAssetVariables> {
  const { activeUser } = useActiveUser();
  const queryClient = useQueryClient();
  return useMutation<Asset, ApiError, PatchAssetVariables>({
    mutationFn: ({ assetId, body }: PatchAssetVariables) =>
      requireUser(activeUser, (user) => client.patchAsset(user, assetId, body)),
    onSuccess: (_asset, variables) => {
      if (activeUser === null) {
        return;
      }
      invalidatePrefixes(queryClient, [assetsKey(activeUser), assetKey(activeUser, variables.assetId)]);
    },
  });
}

/** Variables for the unified add (files and/or text, optional account scope). */
export interface AddVariables {
  readonly files?: File[];
  readonly text?: string;
  readonly account_id?: string;
}

/**
 * D5: unified add → `["assets", uid]` (committed assets appear) AND
 * `["batches", uid]` (a `statement_preview` outcome creates an import batch).
 * Exactly these two prefixes — nothing else changes.
 */
export function useAdd(): UseMutationResult<AddItemOutcome[], ApiError, AddVariables> {
  const { activeUser } = useActiveUser();
  const queryClient = useQueryClient();
  return useMutation<AddItemOutcome[], ApiError, AddVariables>({
    mutationFn: (body: AddVariables) =>
      requireUser(activeUser, (user) => client.addItems(user, body)),
    onSuccess: () => {
      if (activeUser === null) {
        return;
      }
      invalidatePrefixes(queryClient, [assetsKey(activeUser), batchesKey(activeUser)]);
    },
  });
}

// ---------------------------------------------------------------------------
// Search queries (read-only, no invalidation)
// ---------------------------------------------------------------------------

/** `["search-quick", uid, q, limit]` — quick search hits for the typeahead. */
export function searchQuickKey(
  userId: string | null,
  q: string,
  limit: number,
): readonly ['search-quick', string | null, string, number] {
  return ['search-quick', userId, q, limit];
}

/**
 * Paged-search filters in UI shape. The wire names (`purchase_from`,
 * `purchase_to`, `has_documents`, `doc_classification`) are mapped in the
 * query function; the key keeps the UI shape (mirrors `MovementFilterInput`).
 */
export interface SearchFilterInput {
  readonly category?: string;
  readonly brand?: string;
  readonly purchaseFrom?: string;
  readonly purchaseTo?: string;
  readonly warrantyStatus?: string;
  readonly hasDocuments?: boolean;
  readonly docClassification?: 'invoice' | 'receipt' | 'warranty' | 'amc' | 'statement' | 'other';
}

/** Always all seven keys present (undefined when unset) — stable key shape. */
function normalizeSearchFilters(filters: SearchFilterInput | undefined): SearchFilterInput {
  return {
    category: filters?.category,
    brand: filters?.brand,
    purchaseFrom: filters?.purchaseFrom,
    purchaseTo: filters?.purchaseTo,
    warrantyStatus: filters?.warrantyStatus,
    hasDocuments: filters?.hasDocuments,
    docClassification: filters?.docClassification,
  };
}

/** `["search", uid, q, {filters}, page, pageSize]` — paged search results. */
export function searchKey(
  userId: string | null,
  q: string,
  page: number,
  pageSize: number,
  filters?: SearchFilterInput,
): readonly ['search', string | null, string, SearchFilterInput, number, number] {
  return ['search', userId, q, normalizeSearchFilters(filters), page, pageSize];
}

/** `["reviews", uid, status]` — ingest review list. */
export function reviewsKey(
  userId: string | null,
  status: 'pending' | 'approved' | 'rejected',
): readonly ['reviews', string | null, 'pending' | 'approved' | 'rejected'] {
  return ['reviews', userId, status];
}

/** `["review", uid, id]` — a single ingest review. */
export function reviewKey(
  userId: string | null,
  id: string,
): readonly ['review', string | null, string] {
  return ['review', userId, id];
}

/**
 * Quick search (typeahead). Disabled while no user is active or when the
 * query is blank/whitespace (mirrors the spec's "no request for blank").
 */
export function useQuickSearch(q: string, limit = 10): UseQueryResult<{ results: ReadonlyArray<import('./schema').SearchHit> }, Error> {
  const { activeUser } = useActiveUser();
  const trimmed = q.trim();
  return useQuery({
    queryKey: searchQuickKey(activeUser, trimmed, limit),
    enabled: activeUser !== null && trimmed.length > 0,
    queryFn: () => requireUser(activeUser, (user) => client.quickSearch(user, { q: trimmed, limit })),
  });
}

/**
 * Paged search with structured filters. Disabled while no user is active or
 * when the query is blank. `placeholderData: keepPreviousData` keeps the
 * previous results on screen during filter/page changes (matches
 * `useMovements`).
 *
 * Signature: `useSearch(q, filters?, page?, pageSize?)`. The second argument
 * accepts EITHER the structured filters (`SearchFilterInput`) OR a page number
 * (back-compat with the pre-filters `useSearch(q, page, pageSize)` call shape
 * used by `search-results-page.tsx`): `useSearch('q', 2, 20)` ≡
 * `useSearch('q', undefined, 2, 20)`. Filters are normalized into the query
 * key (D5) so any filter change re-queries; only supplied fields are mapped to
 * wire params (`category`, `purchase_from`, …) in the query function.
 */
export function useSearch(
  q: string,
  filtersOrPage?: SearchFilterInput | number,
  pageOrPageSize = 1,
  pageSize = 20,
): UseQueryResult<SearchResultsPage, Error> {
  const { activeUser } = useActiveUser();
  const trimmed = q.trim();
  const isLegacy = typeof filtersOrPage === 'number';
  const filters = isLegacy ? undefined : filtersOrPage;
  const page = isLegacy ? filtersOrPage : pageOrPageSize;
  // In legacy mode `pageOrPageSize` is the pageSize (old 3rd arg); in
  // structured mode `pageSize` is the 4th arg.
  const resolvedPageSize = isLegacy ? pageOrPageSize : pageSize;
  const normalized = normalizeSearchFilters(filters);
  const params = {
    q: trimmed,
    page,
    page_size: resolvedPageSize,
    category: normalized.category,
    brand: normalized.brand,
    purchase_from: normalized.purchaseFrom,
    purchase_to: normalized.purchaseTo,
    warranty_status: normalized.warrantyStatus,
    has_documents: normalized.hasDocuments,
    doc_classification: normalized.docClassification,
  };
  return useQuery({
    queryKey: searchKey(activeUser, trimmed, page, resolvedPageSize, filters),
    enabled: activeUser !== null && trimmed.length > 0,
    placeholderData: keepPreviousData,
    queryFn: () => requireUser(activeUser, (user) => client.search(user, params)),
  });
}

/** `["reviews", uid, status]` — the active user's reviews by status. */
export function useReviews(status: 'pending' | 'approved' | 'rejected' = 'pending'): UseQueryResult<ReadonlyArray<import('./schema').IngestReview>, Error> {
  const { activeUser } = useActiveUser();
  return useQuery({
    queryKey: reviewsKey(activeUser, status),
    enabled: activeUser !== null,
    queryFn: () => requireUser(activeUser, (user) => client.listReviews(user, { status })),
  });
}

/** `["review", uid, id]` — one ingest review. */
export function useReview(id: string): UseQueryResult<import('./schema').IngestReview, Error> {
  const { activeUser } = useActiveUser();
  return useQuery({
    queryKey: reviewKey(activeUser, id),
    enabled: activeUser !== null && id !== '',
    queryFn: () => requireUser(activeUser, (user) => client.getReview(user, id)),
  });
}

/** Variables for approve/reject. */
export interface ReviewIdVariables {
  readonly reviewId: string;
}

/**
 * D5: approve invalidates `["reviews", uid]`, `["review", uid, id]`, AND
 * `["assets", uid]` (approve creates/merges an Asset + Document, mirroring
 * `useCommitBatch`'s multi-prefix invalidation).
 */
export function useApproveReview(): UseMutationResult<import('./schema').ApproveReviewResponse, ApiError, ReviewIdVariables> {
  const { activeUser } = useActiveUser();
  const queryClient = useQueryClient();
  return useMutation<import('./schema').ApproveReviewResponse, ApiError, ReviewIdVariables>({
    mutationFn: ({ reviewId }: ReviewIdVariables) =>
      requireUser(activeUser, (user) => client.approveReview(user, reviewId)),
    onSuccess: (_data, variables) => {
      if (activeUser === null) {
        return;
      }
      invalidatePrefixes(queryClient, [
        reviewsPrefix(activeUser),
        reviewKey(activeUser, variables.reviewId),
        assetsKey(activeUser),
      ]);
    },
  });
}

/** D5: reject invalidates `["reviews", uid]` and `["review", uid, id]` only. */
export function useRejectReview(): UseMutationResult<import('./schema').IngestReview, ApiError, ReviewIdVariables> {
  const { activeUser } = useActiveUser();
  const queryClient = useQueryClient();
  return useMutation<import('./schema').IngestReview, ApiError, ReviewIdVariables>({
    mutationFn: ({ reviewId }: ReviewIdVariables) =>
      requireUser(activeUser, (user) => client.rejectReview(user, reviewId)),
    onSuccess: (_data, variables) => {
      if (activeUser === null) {
        return;
      }
      invalidatePrefixes(queryClient, [
        reviewsPrefix(activeUser),
        reviewKey(activeUser, variables.reviewId),
      ]);
    },
  });
}

/** Prefix of EVERY reviews key (any status) — the D5 invalidation unit. */
function reviewsPrefix(userId: string): readonly ['reviews', string] {
  return ['reviews', userId];
}
