/**
 * Shared data-layer plumbing for the TanStack Query hooks.
 *
 * asset-management-v2 (modular-structure): the per-feature hooks have been
 * co-located with their features. This file is the SHARED home for:
 *
 *  - the query-key builders (D5) + `requireUser` + filter normalizers + the
 *    wire-shape input interfaces — the single source of truth every feature
 *    hook imports;
 *  - `useQuickSearch` — served to the non-feature `features/docs/search/
 *    quick-search.tsx` shell component (no owning feature);
 *  - the ORPHAN mutation hooks that no feature page imports yet
 *    (`useUploadDocument`, `useUnlinkMovement`, `useDeleteAsset`,
 *    `useMergeAsset`, `usePatchAsset`, `useReview`).
 *
 * The feature-facing query/mutation hooks live alongside their features:
 *   - `@/features/docs/hooks`         shared multi-feature (useAssets,
 *                                     useAssetDocuments, useAccounts)
 *   - `@/features/assets/use-asset`   useAsset
 *   - `@/features/finance/hooks`      the 11 finance hooks
 *   - `@/features/add/hooks`          useRestoreAsset, useAdd
 *   - `@/features/search/use-search`  useSearch
 *   - `@/features/reviews/hooks`      useReviews, useApproveReview,
 *                                     useRejectReview
 *
 * The D5 invalidation map each mutation honors is unchanged; the map table is
 * kept here as the reference:
 *
 *   | hook                | invalidated prefixes                                              |
 *   | ------------------- | ----------------------------------------------------------------- |
 *   | useUploadDocument   | ["assets", uid]                                                   |
 *   | useCreateAccount    | ["accounts", uid]                                                 |
 *   | useCreateMovement   | ["movements", uid], ["accounts", uid]                             |
 *   | usePatchDescription | ["movements", uid], ["accounts", uid]                             |
 *   | useDeleteMovement   | ["movements", uid], ["accounts", uid]                             |
 *   | useLinkMovement     | ["movements", uid], ["accounts", uid]                             |
 *   | useUnlinkMovement   | ["movements", uid], ["accounts", uid]                             |
 *   | useUploadStatement  | ["batches", uid], ["batch", uid, id]                              |
 *   | useCommitBatch      | ["batches", uid], ["batch", uid, id], ["movements", uid], ["accounts", uid] |
 *   | useDiscardBatch     | ["batches", uid], ["batch", uid, id]                              |
 *   | useDeleteAsset      | ["assets", uid], ["asset", uid, id]                               |
 *   | useRestoreAsset     | ["assets", uid], ["asset", uid, id]                               |
 *   | useMergeAsset       | ["assets", uid], ["asset", uid, survivorId], ["asset", uid, duplicateId] |
 *   | usePatchAsset       | ["assets", uid], ["asset", uid, id]                               |
 *   | useAdd              | ["assets", uid], ["batches", uid]                                 |
 *   | useApproveReview    | ["reviews", uid], ["review", uid, id], ["assets", uid]            |
 *   | useRejectReview     | ["reviews", uid], ["review", uid, id]                             |
 *
 * The `["movements", uid]` prefix deliberately carries NO filter element, so
 * it matches every filter variant of the movements key.
 *
 * All API calls go through typed per-operation functions from client.ts
 * (generated by orval), replacing the previous apiJson/apiVoid path-string bridge.
 */
import { useMutation, useQuery, useQueryClient, type QueryClient, type UseMutationResult, type UseQueryResult } from '@tanstack/react-query';
import * as client from './client';
import { uploadDocument } from './upload';
import type { UploadDocumentResult } from './upload';
import { ApiError } from './errors';
import { useActiveUser } from '../../context/active-user';
import type { DocumentStatus } from './client';
import type {
  Asset,
  MergeRequest,
  PatchAssetRequest,
} from './schema';

// ---------------------------------------------------------------------------
// Query keys (D5) — every key carries the active user id (D4)
// ---------------------------------------------------------------------------

/** `["assets", uid]` — the active user's assets. */
export function assetsKey(userId: string | null): readonly ['assets', string | null] {
  return ['assets', userId];
}

/** `["asset", uid, id]` — one asset. */
export function assetKey(userId: string | null, assetId: string): readonly ['asset', string | null, string] {
  return ['asset', userId, assetId];
}

/** `["asset-docs", uid, id]` — the documents of one asset. */
export function assetDocsKey(
  userId: string | null,
  assetId: string,
): readonly ['asset-docs', string | null, string] {
  return ['asset-docs', userId, assetId];
}

/** `["accounts", uid]` — the active user's finance accounts. */
export function accountsKey(userId: string | null): readonly ['accounts', string | null] {
  return ['accounts', userId];
}

/**
 * Movement list filters in UI shape. The wire names (`account_id`, `from`,
 * `to`) are mapped in the query function; the key keeps the UI shape
 * (D5: `{accountId, from, to}`).
 */
export interface MovementFilterInput {
  readonly accountId?: string;
  readonly from?: string;
  readonly to?: string;
}

/** Always all three keys present (undefined when unset) — stable key shape. */
function normalizeFilters(filters: MovementFilterInput | undefined): MovementFilterInput {
  return { accountId: filters?.accountId, from: filters?.from, to: filters?.to };
}

/** `["movements", uid, {accountId, from, to}]` — movements with the filters. */
export function movementsKey(
  userId: string | null,
  filters?: MovementFilterInput,
): readonly ['movements', string | null, MovementFilterInput] {
  return ['movements', userId, normalizeFilters(filters)];
}

/**
 * Prefix of EVERY movements key (any filter set) — the D5 invalidation unit.
 * Without the filter element it matches all filter variants.
 */
export function movementsPrefix(userId: string | null): readonly ['movements', string | null] {
  return ['movements', userId];
}

/**
 * Prefix of EVERY reviews key (any status) — the D5 invalidation unit.
 * Without the status element it matches all status variants.
 */
export function reviewsPrefix(userId: string | null): readonly ['reviews', string | null] {
  return ['reviews', userId];
}

/** `["batches", uid]` — the import batch history. */
export function batchesKey(userId: string | null): readonly ['batches', string | null] {
  return ['batches', userId];
}

/**
 * Document list filters in UI shape (documents feature, task 8.1). `status`
 * is the derived lifecycle state; `q` a filename substring.
 */
export interface DocumentFilterInput {
  readonly status?: DocumentStatus;
  readonly q?: string;
}

/** Always both keys present (undefined when unset) — stable key shape. */
function normalizeDocumentFilters(filters: DocumentFilterInput | undefined): DocumentFilterInput {
  return { status: filters?.status, q: filters?.q };
}

/** `["documents", uid, {status, q}]` — documents with the filters. */
export function documentsKey(
  userId: string | null,
  filters?: DocumentFilterInput,
): readonly ['documents', string | null, DocumentFilterInput] {
  return ['documents', userId, normalizeDocumentFilters(filters)];
}

/**
 * Prefix of EVERY documents key (any filter set) — the D5 invalidation unit.
 * Without the filter element it matches all filter variants.
 */
export function documentsPrefix(userId: string | null): readonly ['documents', string | null] {
  return ['documents', userId];
}

/** `["batch", uid, id]` — one import batch. */
export function batchKey(userId: string | null, batchId: string): readonly ['batch', string | null, string] {
  return ['batch', userId, batchId];
}

// ---------------------------------------------------------------------------
// Request plumbing
// ---------------------------------------------------------------------------

/**
 * Run `fetchWithUser` for the active user. Queries are only enabled, and the
 * UI only offers mutations, while a user is active, so the rejection is
 * defensive; it keeps the fetchers null-free without non-null assertions.
 */
export function requireUser<T>(userId: string | null, fetchWithUser: (user: string) => Promise<T>): Promise<T> {
  if (userId === null) {
    return Promise.reject(new Error('No active user selected'));
  }
  return fetchWithUser(userId);
}

// ---------------------------------------------------------------------------
// Invalidation helper (D5)
// ---------------------------------------------------------------------------

/**
 * Invalidate EXACTLY the given key prefixes (D5). One `invalidateQueries`
 * call per prefix keeps the "exactly these prefixes" contract observable.
 */
export function invalidatePrefixes(queryClient: QueryClient, prefixes: ReadonlyArray<readonly unknown[]>): void {
  for (const prefix of prefixes) {
    // Fire-and-forget: invalidation only schedules refetches.
    void queryClient.invalidateQueries({ queryKey: prefix });
  }
}

/** The D5 prefixes shared by every movement mutation. */
export function movementInvalidations(userId: string): ReadonlyArray<readonly unknown[]> {
  return [movementsPrefix(userId), accountsKey(userId)];
}

// ---------------------------------------------------------------------------
// Orphan mutations (no feature importer yet — kept in the shared home)
// ---------------------------------------------------------------------------

/**
 * D5: document upload → `["assets", uid]`. The upload goes through the XHR
 * helper (D6) so progress can be reported.
 */
export interface UploadDocumentVariables {
  readonly file: File;
  readonly onProgress?: (event: { loaded: number; total: number }) => void;
}

export function useUploadDocument(): UseMutationResult<UploadDocumentResult, ApiError, UploadDocumentVariables> {
  const { activeUser } = useActiveUser();
  const queryClient = useQueryClient();
  return useMutation<UploadDocumentResult, ApiError, UploadDocumentVariables>({
    mutationFn: ({ file, onProgress }: UploadDocumentVariables) =>
      requireUser(activeUser, (user) => uploadDocument(user, file, onProgress ?? (() => undefined))),
    onSuccess: () => {
      if (activeUser === null) {
        return;
      }
      invalidatePrefixes(queryClient, [assetsKey(activeUser)]);
    },
  });
}

/** Variables identifying one movement (delete/unlink). */
export interface MovementIdVariables {
  readonly movementId: string;
}

/**
 * D5: movement unlink → `["movements", uid]` + `["accounts", uid]`.
 */
export function useUnlinkMovement(): UseMutationResult<void, ApiError, MovementIdVariables> {
  const { activeUser } = useActiveUser();
  const queryClient = useQueryClient();
  return useMutation<void, ApiError, MovementIdVariables>({
    mutationFn: ({ movementId }: MovementIdVariables) =>
      requireUser(activeUser, (user) => client.unlinkMovement(user, movementId)),
    onSuccess: () => {
      if (activeUser === null) {
        return;
      }
      invalidatePrefixes(queryClient, movementInvalidations(activeUser));
    },
  });
}

/** Variables identifying one asset (delete/restore/patch). */
export interface AssetIdVariables {
  readonly assetId: string;
}

/**
 * D5: asset soft-delete → `["assets", uid]` + `["asset", uid, id]`.
 */
export function useDeleteAsset(): UseMutationResult<void, ApiError, AssetIdVariables> {
  const { activeUser } = useActiveUser();
  const queryClient = useQueryClient();
  return useMutation<void, ApiError, AssetIdVariables>({
    mutationFn: ({ assetId }: AssetIdVariables) =>
      requireUser(activeUser, (user) => client.deleteAsset(user, assetId)),
    onSuccess: (_data, variables) => {
      if (activeUser === null) {
        return;
      }
      invalidatePrefixes(queryClient, [assetsKey(activeUser), assetKey(activeUser, variables.assetId)]);
    },
  });
}

/** Variables for merging a duplicate asset into a survivor. */
export interface MergeAssetVariables {
  readonly assetId: string;
  readonly duplicateAssetId: string;
}

/**
 * D5: asset merge → `["assets", uid]` + `["asset", uid, survivorId]` AND
 * `["asset", uid, duplicateId]` (the duplicate's row changes to merged-into,
 * so its detail must refetch too).
 */
export function useMergeAsset(): UseMutationResult<Asset, ApiError, MergeAssetVariables> {
  const { activeUser } = useActiveUser();
  const queryClient = useQueryClient();
  return useMutation<Asset, ApiError, MergeAssetVariables>({
    mutationFn: ({ assetId, duplicateAssetId }: MergeAssetVariables) => {
      const body: MergeRequest = { duplicate_asset_id: duplicateAssetId };
      return requireUser(activeUser, (user) => client.mergeAsset(user, assetId, body));
    },
    onSuccess: (_asset, variables) => {
      if (activeUser === null) {
        return;
      }
      invalidatePrefixes(queryClient, [
        assetsKey(activeUser),
        assetKey(activeUser, variables.assetId),
        assetKey(activeUser, variables.duplicateAssetId),
      ]);
    },
  });
}

/** Variables for the asset correction PATCH. */
export interface PatchAssetVariables {
  readonly assetId: string;
  readonly body: PatchAssetRequest;
}

/**
 * D5: asset patch (user corrections incl. `asset_category`) →
 * `["assets", uid]` + `["asset", uid, id]`.
 */
export function usePatchAsset(): UseMutationResult<Asset, ApiError, PatchAssetVariables> {
  const { activeUser } = useActiveUser();
  const queryClient = useQueryClient();
  return useMutation<Asset, ApiError, PatchAssetVariables>({
    mutationFn: ({ assetId, body }: PatchAssetVariables) =>
      requireUser(activeUser, (user) => client.patchAsset(user, assetId, body)),
    onSuccess: (_asset, variables) => {
      if (activeUser === null) {
        return;
      }
      invalidatePrefixes(queryClient, [assetsKey(activeUser), assetKey(activeUser, variables.assetId)]);
    },
  });
}

// ---------------------------------------------------------------------------
// Search / reviews (shared plumbing + the non-feature quick-search hook)
// ---------------------------------------------------------------------------

/** `["search-quick", uid, q, limit]` — quick search hits for the typeahead. */
export function searchQuickKey(
  userId: string | null,
  q: string,
  limit: number,
): readonly ['search-quick', string | null, string, number] {
  return ['search-quick', userId, q, limit];
}

/**
 * Paged-search filters in UI shape. The wire names (`purchase_from`,
 * `purchase_to`, `has_documents`, `doc_classification`) are mapped in the
 * query function; the key keeps the UI shape (mirrors `MovementFilterInput`).
 */
export interface SearchFilterInput {
  readonly category?: string;
  readonly brand?: string;
  readonly purchaseFrom?: string;
  readonly purchaseTo?: string;
  readonly warrantyStatus?: string;
  readonly hasDocuments?: boolean;
  readonly docClassification?: 'invoice' | 'receipt' | 'warranty' | 'amc' | 'statement' | 'other';
}

/** Always all seven keys present (undefined when unset) — stable key shape. */
export function normalizeSearchFilters(filters: SearchFilterInput | undefined): SearchFilterInput {
  return {
    category: filters?.category,
    brand: filters?.brand,
    purchaseFrom: filters?.purchaseFrom,
    purchaseTo: filters?.purchaseTo,
    warrantyStatus: filters?.warrantyStatus,
    hasDocuments: filters?.hasDocuments,
    docClassification: filters?.docClassification,
  };
}

/** `["search", uid, q, {filters}, page, pageSize]` — paged search results. */
export function searchKey(
  userId: string | null,
  q: string,
  page: number,
  pageSize: number,
  filters?: SearchFilterInput,
): readonly ['search', string | null, string, SearchFilterInput, number, number] {
  return ['search', userId, q, normalizeSearchFilters(filters), page, pageSize];
}

/** `["reviews", uid, status]` — ingest review list. */
export function reviewsKey(
  userId: string | null,
  status: 'pending' | 'approved' | 'rejected',
): readonly ['reviews', string | null, 'pending' | 'approved' | 'rejected'] {
  return ['reviews', userId, status];
}

/** `["review", uid, id]` — a single ingest review. */
export function reviewKey(
  userId: string | null,
  id: string,
): readonly ['review', string | null, string] {
  return ['review', userId, id];
}

/**
 * Quick search (typeahead). Disabled while no user is active or when the
 * query is blank/whitespace (mirrors the spec's "no request for blank").
 * Serves the non-feature `features/docs/search/quick-search.tsx` shell
 * component (no owning feature).
 */
export function useQuickSearch(q: string, limit = 10): UseQueryResult<{ results: ReadonlyArray<import('./schema').SearchHit> }, Error> {
  const { activeUser } = useActiveUser();
  const trimmed = q.trim();
  return useQuery({
    queryKey: searchQuickKey(activeUser, trimmed, limit),
    enabled: activeUser !== null && trimmed.length > 0,
    queryFn: () => requireUser(activeUser, (user) => client.quickSearch(user, { q: trimmed, limit })),
  });
}

/** `["review", uid, id]` — one ingest review. */
export function useReview(id: string): UseQueryResult<import('./schema').IngestReview, Error> {
  const { activeUser } = useActiveUser();
  return useQuery({
    queryKey: reviewKey(activeUser, id),
    enabled: activeUser !== null && id !== '',
    queryFn: () => requireUser(activeUser, (user) => client.getReview(user, id)),
  });
}
